// This file is automatically generated by vscode-react-native@0.2.4
// Please do not modify it manually. All changes will be lost.
try {
    var path = require("path");
    var Launcher = require("C:\\Users\\shawn\\.vscode\\extensions\\vsmobile.vscode-react-native-0.2.4\\out\\debugger\\launcher.js").Launcher;
    new Launcher("d:\\work\\16fall_Semester\\EC601\\finalProject\\DirtyDrawz", "d:\\work\\16fall_Semester\\EC601\\finalProject\\DirtyDrawz").launch();
} catch (e) {
    throw new Error("Unable to launch application. Try deleting .vscode/launchReactNative.js and restarting vscode.");
}